# Generated by Django 5.0.6 on 2024-06-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='user_id',
            new_name='user',
        ),
    ]
