# Generated by Django 5.0.6 on 2024-06-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.BooleanField()),
                ('language', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorisation.user')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
