# Generated by Django 5.0.6 on 2024-06-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_rename_user_id_pet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('weight', models.FloatField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'db_table': 'weight_records',
            },
        ),
    ]
