# Generated by Django 5.0.6 on 2024-06-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        ('pets', '0002_rename_user_id_pet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFeed',
            fields=[
                ('pet_feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_quanity', models.FloatField()),
                ('feed_time', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'db_table': 'pet_feeds',
            },
        ),
    ]
